name: szhassistant
description: szh Assistant In Your APP
version: 0.0.1
auther: Sadiq Abdullah Hassan
homepage: https://github.com/zangestu2Eszh/szhassistant


environment:
  sdk: '>=2.19.1 <=3.3.10'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts//Cairo/Cairo-Regular.ttf


