name: szhassistant
description: szh Assistant in your APP

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <=3.3.10'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:

  uses-material-design: true

  # MyFiles:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # MyFonts:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

