name: szhassistant
description: szh Assistant is used to facilitate the creation of applications and contains some basic things in each application, such as the appbar and dialog, the most used text sizes and the most used colors, and it is also responsive with all screen sizes, and it also contains font Cairo
version: 0.0.1
auther: Zangestu
publish_to: Zangestu
homepage: https://github.com/zangestu2Eszh/szhassistant


environment:
  sdk: '>=2.19.1 <=3.3.10'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts//Cairo/Cairo-Regular.ttf


